
name: Mirror to Bitbucket

on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
          
      - name: Disable GPG Signing
        run: git config --global commit.gpgsign false
        
      - name: Mirror to Bitbucket
        uses: heussd/mirror-to-bitbucket-github-action@v2
        with:
          username: vigneshm1683
          spacename: bitbucketgitconnect
          repository: gitbitbucketconnect
          password: ${{ secrets.BITBUCKET_PASSWORD }}
