
name: Mirror to Bitbucket

on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
          
      - name: Configure Git User (Set Bitbucket User as "vigneshm1683")
        run: |
          git config --global commit.gpgsign false
          git config --global tag.gpgSign false
          git config --global user.email "vignesh.m1683@gmail.com"
          git config --global user.name "vigneshm1683"
        
      - name: Mirror to Bitbucket
        uses: heussd/mirror-to-bitbucket-github-action@v2
        with:
          username: vigneshm1683
          spacename: bitbucketgitconnect
          repository: gitbitbucketconnect
          password: ${{ secrets.BITBUCKET_PASSWORD }}
