
name: Mirror to Bitbucket

on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
          
      - name: Configure Git User (Force Bitbucket User as "vigneshm1683")
        run: |
          git config --global user.name "vigneshm1683"
          git config --global user.email "vignesh.m1683@gmail.com"
          git config --global commit.gpgsign false
          git config --global tag.gpgSign false

      - name: Reformat Git History to Change Committer
        run: |
          git checkout main
          git commit --amend --no-edit --author="vigneshm1683 <vignesh.m1683@gmail.com>"
          git rebase --root --committer-date-is-author-date
        
      - name: Mirror to Bitbucket
        uses: heussd/mirror-to-bitbucket-github-action@v2
        with:
          username: vigneshm1683
          spacename: bitbucketgitconnect
          repository: gitbitbucketconnect
          password: ${{ secrets.BITBUCKET_PASSWORD }}
